import { RecurringIcon } from './RecurringIcon'
import { UpcomingIcon } from './UpcomingIcon'

interface Props {
  recurring?: boolean
  upcoming?: boolean
  size?: number
  className?: string
}

// Small indicator icons shown next to (or on) an expense: a round-arrow for
// ones generated by a recurring expense, an up-arrow for ones dated in the
// future (planned but not yet happened).
export function EntryBadges({ recurring, upcoming, size = 12, className }: Props) {
  if (!recurring && !upcoming) return null
  return (
    <span className={`entry-badge-icons${className ? ` ${className}` : ''}`}>
      {recurring && <RecurringIcon size={size} />}
      {upcoming && <UpcomingIcon size={size} />}
    </span>
  )
}
